version: '3.1'

services:

  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./server/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tasksList